on:
  push:
    branches:
    - master
name: Publish the Docker image
jobs:
  publish_image:
    name: Publish the Docker image
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@f6ce2afa7079cb075a124c93c79d61779d845782
    - name: Docker login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
    - name: Docker build
      run: |
        docker build -t graphhopper/graphhopper-load-test-fake-backend .
    - name: Docker push
      run: |
        docker push graphhopper/graphhopper-load-test-fake-backend
